source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!



target 'Bluetooth-Interaction' do
    pod 'SnapKit'
    pod 'ChameleonFramework/Swift'
    pod 'Charts'
end

target 'Bluetooth-InteractionTests' do
    
end

target 'Bluetooth-InteractionUITests' do
    
end

