source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!



target 'Bluetooth-Interaction' do
	pod 'SnapKit', '~> 0.15.0'
	pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
end

target 'Bluetooth-InteractionTests' do

end

target 'Bluetooth-InteractionUITests' do

end

